### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by fYaH-r0ze** [vojtamolda/homebridge-bluetooth#1]
I'm getting an error with the Bluetooth-hci-socket about operating system not supported

**Comment by fYaH-r0ze** [comment]
I'm using macOS 10.12.

**Comment by vojtamolda** [comment]
Hello!
Thanks for opening the 1st issue :) Does your mac have built-in support for Bluetooth 4.0 (Low Energy)?

**Comment by fYaH-r0ze** [comment]
Well I use a lot of BLE devices with my mac, so I believe it should have built in support. It's pretty new and works with handoff etc so, yes it does have built in BLE support

**Comment by fYaH-r0ze** [comment]
installing Noble throws the following:

sudo npm install -g noble
Password:
/usr/local/lib
└── noble@1.7.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@^0.5.1 (node_modules/noble/node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

If i run some test code to check if noble was successfully installed, I get an error saying that package "noble" was not found - so my guess is that it didn't install?

**Comment by vojtamolda** [comment]
Hmm... That's puzzling. I'm not very familiar with _noble_ internals and I saw you already opened an issue there, so hopefully Sandeep will be able to help. Everything installs fine on my macOS 10.12, but _npm_ skips optional dependency to _bluetooth-hci-socket_.

![npm-install-noble](https://cloud.githubusercontent.com/assets/8467740/20239064/bcd8b052-a8bd-11e6-8bc7-b6ea1799d337.png)

BTW, You can get a list of installed packages by running `npm --list` and `| grep noble` to see if it really installed.

**Comment by fYaH-r0ze** [comment]
Hmm ok. I'm still figuring this out, but I think the bluetooth part is working now. I'm still trying to understand how the whole plugin stuff works though.

I'm trying to get this to work with a BLE accessory that I created based on the MBed platform. Would you mind being contacted to lend some help?
