### ISSUE TITLE
Usage case Siri remote

### ISSUE THREAD

**Issue by kapps7** [vojtamolda/homebridge-bluetooth#10]
Hi,

Could this be used to trigger the Siri remote to execute buttons ?

**Comment by vojtamolda** [comment]
Hello @kapps7,

Yes, you can use the Siri Remote to control any of the [example devices](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples) in this repository.  Each of them "pretends" to be a standard _HomeKit_ accessory behind a _Homebridge_ server that forwards the BLE requests and acts as a bridge.

**Comment by kapps7** [comment]
I see thanks. I actually wanted to be able to use the Siri remote to simply control the Apple TV so I can sequence a series of buttons via HomeKit
