### ISSUE TITLE
Infinitely stuck activity spinner in the Home app on iOS

### ISSUE THREAD

**Issue by weeteniz** [vojtamolda/homebridge-bluetooth#13]
Hi,

I'm trying to develop my own window covering BLE peripheral/accessory. So far I have:

- Set up Homebridge on Raspberry Pi 2 with a bluetooth dongle. Homebridge loads fine and finds the BLEPeripheral (in this case RedBear Blend Micro with Nordic nRF8001)

Here's the `config.json`:
```js
{
"bridge": {
  "name": "Raspberry Pi 2",
  "username": "00:13:EF:80:00:12",
  "port": 51826,
  "pin": "031-45-154"
  },
  
"description": "Raspberry Pi 2 Homebridge-Bluetooth",

"platforms": [
{
  "platform": "Bluetooth",
  "accessories": [
    {
    "name": "Smart Shades",
    "name_note": "Name of the accessory as shown in the Home app on iOS.",

    "address": "D0:5F:2E:E2:11:22",
    "address_note": "Bluetooth address of the accessory. Non-matching devices are ignored.",

    "services": [
      {
      "name": "Smart Blinds",
      "name_note": "Name of the service as shown in the Home app on iOS.",

      "type": "WindowCovering",
      "type_note1": "Type of the service - i.e. Lightbulb, Switch, Lock, HumiditySensor, ...",
      "type_note2": "Must match this list - https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js",
      "type_note3": "Service.Lightbulb has a mandatory On characteristic and Brightness, Hue and Saturation are optional.",

      "UUID": "A7B10010-EEEE-5377-FF6C-D104768A1214",
      "UUID_note": "Bluetooth UUID of the service. Capitalization and dashes doesn't matter.",

      "characteristics": [
      {
        "type": "CurrentPosition",
        "type_note1": "Type of the characteristic - i.e. On, Brightness, CurrentHumidity, CurrentTemperature, ...",
        "type_note2": "Must match this list - https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js",
        "type_note3": "Characteristic.On is a BOOL value and expects READ, WRITE and NOTIFY permissions.",

        "UUID": "A7B10011-EEEE-5377-FF6C-D104768A1214",
        "UUID_note": "Bluetooth UUID of the characteristic. Capitalization and dashes doesn't matter."
      },
      {
        "type": "TargetPosition",
        "type_note1": "Type of the characteristic - i.e. On, Brightness, CurrentHumidity, CurrentTemperature, ...",
        "type_note2": "Must match this list - https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js",
        "type_note3": "Characteristic.Brightness is an INT value and expects READ, WRITE and NOTIFY permissions.",

        "UUID": "A7B10012-EEEE-5377-FF6C-D104768A1214",
        "UUID_note": "Bluetooth UUID of the characteristic. Capitalization and dashes doesn't matter."
      }
      ],
      "characteristics_note1": "List of Bluetooth characteristics that will be exposed to HomeKit.",
      "characteristics_note2": "Characteristics with non-matching UUIDs are ignored."
      }
    ],
    "services_note1": "List of Bluetooth services that will be exposed to HomeKit.",
    "services_note2": "Services with non-matching UUIDs are ignored."
    }
  ]
  }
  ]
}
```

This is what happens when I launch Homebridge and start interacting with my iPhone:

![screen shot 2017-09-05 at 22 55 43](https://user-images.githubusercontent.com/31673142/30085474-8570a8f2-928e-11e7-81b4-26bf5a8fbc65.png)

- I developed the code with two characteristics TargetPosition and CurrentPosition.
```c
#include <SPI.h>
#include <BLEPeripheral.h>


const int pinLED = 13;

BLEPeripheral ble = BLEPeripheral(6,7,4);
BLEService informationService("180A");
BLECharacteristic modelCharacteristic("2A24", BLERead, "101");
BLECharacteristic manufacturerCharacteristic("2A29", BLERead, "Arduino");
BLECharacteristic serialNumberCharacteristic("2A25", BLERead, "2.71828");

BLEService windowCoveringService("A7B10010-EEEE-5377-FF6C-D104768A1214");
BLEUnsignedCharCharacteristic currentPositionCharacteristic("A7B10011-EEEE-5377-FF6C-D104768A1214", BLERead | BLENotify);
BLEUnsignedCharCharacteristic targetPositionCharacteristic("A7B10012-EEEE-5377-FF6C-D104768A1214", BLEWrite | BLERead | BLENotify);
//BLEUnsignedIntCharacteristic positionStateCharacteristic("A7B10013-EEEE-5377-FF6C-D104768A1214", BLERead | BLENotify);

void setup() {
  
  Serial.begin(115200);
  pinMode(pinLED, OUTPUT);
  digitalWrite(pinLED, true);

  ble.setLocalName("Smart Blinds");
  ble.setAdvertisedServiceUuid(windowCoveringService.uuid());
  ble.addAttribute(informationService);
  ble.addAttribute(modelCharacteristic);
  ble.addAttribute(manufacturerCharacteristic);
  ble.addAttribute(serialNumberCharacteristic);

  ble.addAttribute(windowCoveringService);
  ble.addAttribute(currentPositionCharacteristic);
  ble.addAttribute(targetPositionCharacteristic);
  //ble.addAttribute(positionStateCharacteristic);
  
  currentPositionCharacteristic.setValue(100);
  //positionStateCharacteristic.setValueLE(positionState);

  ble.setEventHandler(BLEConnected, centralConnect);
  ble.setEventHandler(BLEDisconnected, centralDisconnect);
  targetPositionCharacteristic.setEventHandler(BLEWritten, characteristicWrite);
  currentPositionCharacteristic.setEventHandler(BLESubscribed, characteristicSubscribe);

  delay(5000);

  ble.begin();
  Serial.println("Bluetooth on");
}

void loop() {
  ble.poll();
}


void centralConnect(BLECentral& central) {
  Serial.print("Central connected | ");
  Serial.println(central.address());
}

void centralDisconnect(BLECentral& central) {
  Serial.print("Central disconnected | ");
  Serial.println(central.address());
}

void characteristicWrite(BLECentral& central, BLECharacteristic& characteristic) {
  Serial.print("Characteristic written | ");
  Serial.println(characteristic.uuid());
  unsigned char targetPosition = (unsigned char) targetPositionCharacteristic.value();
  Serial.print("Target position set: ");
  Serial.println(targetPosition);
  setBlinds(targetPosition);

}

void characteristicSubscribe(BLECentral& central, BLECharacteristic& characteristic) {

	Serial.println("Characteristic event, subscribed");
	
	//Central subscribes just fine

}

void setBlinds(unsigned char targetPosition) {
	
  //This is where the code to drive the motor will go

  currentPositionCharacteristic.setValue(0);
  
  //When the current position value is set, no notification is sent to the central
  
  Serial.print("Current position: ");
  Serial.println(currentPositionCharacteristic.value());
  digitalWrite(pinLED, false);
  
}
```

When I attempt to open/close the blinds using iOS, the value is written from the central (Homebridge) to the peripheral (RedBear Blend Micro) TargetPosition characteristic as per the first screenshot. Interestingly, TargetPosition characteristic also sends the notification back to the central.

My issue is that whatever I tried, the CurrentPosition characteristic just refuses to send the notification back to the central when its value changes to let the central know that the operation has finished. The central is subscribed to the characteristic because serial prints out some text when the event handler is triggered at the point when the central subscribes.

As the central doesn't get an updated value for the CurrentPosition characteristic, presumably HomeKit has no idea where the blinds are so it simply displays a spinner next to the icon which just doesn't stop spinning (infinite loop).

![smart blinds](https://user-images.githubusercontent.com/31673142/30085968-e2488674-9290-11e7-83c4-dbeb1ce3ec47.png)

Where am I going wrong?

Any help at all would be appreciated!

**Comment by vojtamolda** [comment]
Hello @weeteniz,

What you're doing seems perfectly correct to me. In fact my original version of the [lock example C code](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/examples/lock/arduino101/arduino101.ino) example did it the very same thing as you and was running into the same issue - infinite spinner in the _Home_ app on _iOS_ waiting for the operation to complete.


The way I solved it was just to set a flag to update the target state of the lock for a check in To be honest, I'm not entirely happy with it and if you want to dig into the details.

Thanks for posting the question and for using the plugin!

**Comment by vojtamolda** [comment]
Hello @weeteniz,

What you're doing seems perfectly correct at the first sight. In fact, my original version of the [lock example](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples/lock) handled the `BLEPeripheral` communication the very same way (i.e. during event handlers) and of course I was running into the very same issue - infinite spinner in the _Home_ app on _iOS_ waiting for the operation to complete.

The reason for why this is happening is subtle and not really apparent. The event handler callbacks from the _BLE_ subsystems are not "real" interrupts and in fact are called from within `BLEPeripheral::poll()` method. I solved it by doing all the `BLECharacteristic::get/setValue(LE)(...)` calls inside of the main `loop()` function. The event handlers just set a flag for the main loop that a change of `targetStateCharacteristic`  value occured. You can see the source code [here](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/examples/lock/arduino101/arduino101.ino#L41).

It may not look like it, but lock peripherals work the same way as blinds - there's a target characteristic that _iOS_ writes to when the user issues a lock/unlock command. The current state characteristic then indicates progress of the operation and when both values are equal the spinner disappears. For lock it's only a few predefined values (locked/unlocked/jammed/unknown) for shades it's a percentage (0-100).

To be honest I'm not really happy with the solution, but I don't understand the internals of `BLEPeripheral` library well enough to give you a better explanation than this one.

Thanks for posting the question and for using the plugin! The blinds project looks really cool. I'd be really happy if contribute it as an example. Once it's finished of course 😉

**Comment by weeteniz** [comment]
Thanks for your suggestion. I tried it but I'm still not getting any luck. I've reintroduced the PositionState characteristic that the WindowCovering service uses as I thought that might help but it made no difference.

Here's my updated code based on your suggestion (if I understood it correctly!):

```cpp
#include <SPI.h>
#include <BLEPeripheral.h>

const int pinLED = 13;

BLEPeripheral ble = BLEPeripheral(6,7,4);
BLEService informationService("180A");
BLECharacteristic modelCharacteristic("2A24", BLERead, "101");
BLECharacteristic manufacturerCharacteristic("2A29", BLERead, "Arduino");
BLECharacteristic serialNumberCharacteristic("2A25", BLERead, "2.71828");

BLEService windowCoveringService("A7B10010-EEEE-5377-FF6C-D104768A1214");
BLEUnsignedCharCharacteristic currentPositionCharacteristic("A7B10011-EEEE-5377-FF6C-D104768A1214", BLERead | BLENotify);
BLEUnsignedCharCharacteristic targetPositionCharacteristic("A7B10012-EEEE-5377-FF6C-D104768A1214", BLEWrite | BLERead | BLENotify);
BLEUnsignedCharCharacteristic positionStateCharacteristic("A7B10013-EEEE-5377-FF6C-D104768A1214", BLERead | BLENotify);

bool targetUpdate = false;

void setup() {
  
  Serial.begin(115200);
  pinMode(pinLED, OUTPUT);
  digitalWrite(pinLED, true);

  ble.setLocalName("Smart Blinds");
  ble.setAdvertisedServiceUuid(windowCoveringService.uuid());
  ble.addAttribute(informationService);
  ble.addAttribute(modelCharacteristic);
  ble.addAttribute(manufacturerCharacteristic);
  ble.addAttribute(serialNumberCharacteristic);

  ble.addAttribute(windowCoveringService);
  ble.addAttribute(currentPositionCharacteristic);
  ble.addAttribute(targetPositionCharacteristic);
  ble.addAttribute(positionStateCharacteristic);
  
  //currentPositionCharacteristic.setValue(100);
  positionStateCharacteristic.setValueLE(1);

  ble.setEventHandler(BLEConnected, centralConnect);
  ble.setEventHandler(BLEDisconnected, centralDisconnect);
  targetPositionCharacteristic.setEventHandler(BLEWritten, characteristicWrite);
  currentPositionCharacteristic.setEventHandler(BLESubscribed, characteristicSubscribe);

  delay(5000);

  ble.begin();
  Serial.println("Bluetooth on");
}

void centralConnect(BLECentral& central) {
  Serial.print("Central connected | ");
  Serial.println(central.address());
}

void centralDisconnect(BLECentral& central) {
  Serial.print("Central disconnected | ");
  Serial.println(central.address());
}

void characteristicWrite(BLECentral& central, BLECharacteristic& characteristic) {
  Serial.print("Characteristic written | ");
  Serial.println(characteristic.uuid());
  unsigned char targetPosition = (unsigned char) targetPositionCharacteristic.value();
  Serial.print("Target position set: ");
  Serial.println(targetPosition);
  setBlinds(targetPosition);

}

void characteristicSubscribe(BLECentral& central, BLECharacteristic& characteristic) {

	Serial.println("Characteristic event, subscribed");
	
	//Central subscribes just fine

}

void setBlinds(unsigned char targetPosition) {
	
  //This is where the code to drive the motor will go

  //currentPositionCharacteristic.setValue(0);
  
  //When the current position value is set, no notification is sent to the central
  
  /*Serial.print("Current position: ");
  Serial.println(currentPositionCharacteristic.value());
  digitalWrite(pinLED, false);*/
  
  targetUpdate = true;
  
}

void loop() {
  ble.poll();
  
  if (targetUpdate != false) {
  	
  	unsigned char newTarget = targetPositionCharacteristic.value();
  	currentPositionCharacteristic.setValueLE(newTarget);
  	Serial.print("Current position set to: ");
  	Serial.println(currentPositionCharacteristic.value());
  	
  	unsigned char state = 2;
  	positionStateCharacteristic.setValueLE(state);
  	Serial.print("Current state set to: ");
  	Serial.println(positionStateCharacteristic.value());
  	
  	targetUpdate = false;
  	
  }
  
}
```

**Comment by vojtamolda** [comment]
That's very strange. You got the idea right and I'm puzzled why this doesn't work. I hope to find some time to try your code myself over the next weekend. I'll get back to you.

**Comment by weeteniz** [comment]
Thanks. I've done a bit more experimenting yesterday. I had another look at BLEPeripheral documentation and found the following methods for characteristics:

`bool setValue(const char* value);`

> value - new value as string
> **Returns true on success (central notified/indicated, if applicable), false on failure (cannot be notified/indicated, if applicable)**

> Can the central be notified/indicated of when the value is set. Only applies to characateristics with notify and/or indicate properties when a central is connected and subscribed

```
bool canNotify();
bool canIndicate();
```

I decided to rewrite my code to capture the results of characteristic.setValue() and characteristic.canNotify() methods. The relevant bit of the code now looks like this:

```
void loop() {
  ble.poll();
  
  if (targetUpdate != false) {
  	
  	if (positionStateCharacteristic.canNotify() != 0) { //code enters the block which means canNotify returns 'true'
  		unsigned char state = 2;
	  	bool stateSet = positionStateCharacteristic.setValue(state); //capture success/failure of setValue() notification
	  	Serial.print("Current state set? ");
	  	Serial.println(stateSet); //serial returns 0 which means setValue notification fails
	  	Serial.println(" to: ");
	  	Serial.println(positionStateCharacteristic.value());
  	};
  	
  	unsigned char newTarget = targetPositionCharacteristic.value();
  	bool notifiable = currentPositionCharacteristic.canNotify(); //returns 'true'
  	Serial.print("Can notify? ");
  	Serial.println(notifiable);
  	
  	bool changed = currentPositionCharacteristic.setValue(newTarget);
  	Serial.print("Current position changed? ");
  	Serial.println(changed); //serial returns 0 which means setValue notification fails
  	Serial.print("Current position set to: ");
  	Serial.println(currentPositionCharacteristic.value());
  	
  	targetUpdate = false;
  	
  }
  
}
```

This has made absolutely no difference to how my application functions, however I got some interesting results from the two newly implemented methods.

The result of characteristic.canNotify() comes back as 1 (true).
Crucially, the result of characteristic.setValue() comes back as 0 (failure) meaning that the characteristic could not notify the central.

I've submitted my original post on BLEPeripheral repo but haven't had any responses. I'll add these new results there again to see if anyone replies. I also went through old issues of BLEPeripheral repo and someone mentioned they had an issue with Blend Micro (the exact same controller I'm using) sending notifications. BLEPeripheral library got updated following that issue. I wonder if I'm seeing something similar here.

It would be really good if you could try my code with your setup. If it works for you, it might be controller specific.

**Comment by vojtamolda** [comment]
Hello @weeteniz,

I tested your `config.json` on my _Raspberry Pi 3_ _Homebridge_ server and your sketch on my _Arduino 101_. The result is that everything performs flawlessly. Your first sketch posted here didn't work, but the second one is sending notifications and I don't get any stuck spinners. The position of the blinds is immediately reflected back to the _Home_ app. 

[This](https://github.com/vojtamolda/homebridge-bluetooth/files/1290246/arduino101.zip) is the archive with the exact code and configuration and here's a screenshot: ![blinds](https://user-images.githubusercontent.com/8467740/30246046-b370ac5c-95b3-11e7-92e0-f9bc311fce28.png)

It indeed looks like your issue is hardware specific. So my suggestion would be to try to gradually boil it down to the simplest possible example (i.e. receiving not notifications for a subscribed characteristic when they should be happening) and see at what point along the way it breaks.

**Comment by weeteniz** [comment]
Thank you so much for trying the code and reporting back the results. This has saved me countless hours of banging my head against the wall and going down the wrong path. It does look like there’s an issue with the interaction between the controller and the BLEPeripheral library. I haven’t received a response on the issue I posted there yet but I’ll add the results of your posts there as they are very helpful.

**Comment by vojtamolda** [comment]
You're welcome and good luck with the debugging! This looks like a really nasty bug 🐛.
