### ISSUE TITLE
Use with iPhone Bluetooth presence detection 

### ISSUE THREAD

**Issue by theo-69** [vojtamolda/homebridge-bluetooth#14]
Is it somehow possible to connect my iPhone Bluetooth as Device.
The Idee the homebridge sees when I am home and I can control light or alarm system!

**Comment by vojtamolda** [comment]
Of course you can connect. iPhone controls the entire HomeKit ecosystem and you can setup "Automations" that can get triggered when you get home for instance. See [the official Apple webpage](https://www.apple.com/ios/home/) for more details.

**Comment by theo-69** [comment]
I think you misunderstood me, I would like to see if my iPhone is presence or not. Like a presence detection.
