### ISSUE TITLE
Would it work with August Smart Lock? 

### ISSUE THREAD

**Issue by Kepete** [vojtamolda/homebridge-bluetooth#19]
So, the August SmartLock Pro has homekit compatibility out of the box. But is is really bulky and doesn't fit my door, there just isn't enough room to fit.
August Smart Lock (regular one, the smaller size one, the cheaper one) https://store.august.com/products/august-smart-lock-3rd-generation will fit but it doesn't have Homekit compatibility!

Would this plugin be able to communicate with the SmartLock using bluetooth and make it Homekit compatible?

**Comment by vojtamolda** [comment]
Hello @Kepete,

Unfortunately no. At least not without significant hacking and firmware reflashing on the lock side.

But you can build your own lock by using virtually any electronic lock hardware and an Arduino board. Here's mine: [`examples/lock`](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples/lock). It's been working like a charm for the past ~2 years.

**Comment by eabakker** [comment]
Is this general for all locks? Looking at the Danalock v3 Bluetooth and add it to Homekit with your plugin, instead of getting the Homekit version, so I can use some features not available with the Homekit version. Do you know if this lock works with your plugin?

**Comment by vojtamolda** [comment]
Hello @eabakker,
I don't think the lock works. This plugin is mostly meant for DIY locks where the software running inside of the lock processor can be modified.
