### ISSUE TITLE
let homebridge control a bluetooth projector, streamer?

### ISSUE THREAD

**Issue by QHose** [vojtamolda/homebridge-bluetooth#20]
hi,

Is it somehow possible to let homebridge turn of my (xiaomi mi laser projecter with mi tv) streamer via a `bluetooth turn off` command?

I see a lot of questions on the internet on how to use a bluetooth keyboard with a PI, but I want my PI to send a turn off/on, next etc command to media devices. 

thanks a lot!

**Comment by bencharlesrhys** [comment]
You can connect a device to the projector as a bluetooth keyboard. For instance I've achieved this using the logitech harmony hub and connected the projector as a "Mac" computer profile. I've then found using the sleep keyboard button it will activate the power off, restart window on the Mi Laser Projector - then you need an 'enter' command to turn it off.
