### ISSUE TITLE
How to control electric heater?

### ISSUE THREAD

**Issue by 400HPMustang** [vojtamolda/homebridge-bluetooth#23]
I have an electric heater that I would like to control, the heater uses a bluetooth app for remote control. Is it possible to use this plugin to do that?

I need on/off, heater on/off, and temperature up/down commands

**Comment by vojtamolda** [comment]
Hello @phenomeus,

I'm afraid I don't have the time to take a look at the moment. You'll probably have to figure it yourself if it's still relevant 😉

Cheers,

  Vojta
