### ISSUE TITLE
Bluetooth Shower controls

### ISSUE THREAD

**Issue by JangoBritt** [vojtamolda/homebridge-bluetooth#24]
I have a Mira Mode dual-head shower that I can control via bluetooth, from my phone (preheat, set/view temp, valve select, on/off, etc).

Could this plugin be used to connect that?

How do I decode the data/encode the commands to send to the BLE device?

Can those commands be sniffed when I perform them from my phone?

**Comment by vojtamolda** [comment]
Hello @phenomeus,

I'm afraid I don't have the time to take a look at the moment. You'll probably have to figure it yourself if it's still relevant 😉

Cheers,

  Vojta
