### ISSUE TITLE
NOT AN ISSUE: After Market USB Bluetooth Adapter Mac OS

### ISSUE THREAD

**Issue by samsonrosen** [vojtamolda/homebridge-bluetooth#25]
Hi! 

Just wanted to share that I am running a Macbook Pro Early 2011 which does not support BLE.

On a whim I bought this from Amazon which works perfectly with my Mac. I did remove the AirPort Card from the MacBook Pro (it's on ethernet anyway) to force it to use this device by default but it is working very well with this plugin. Thanks again!

https://www.amazon.co.uk/gp/product/B00LSGUBLI/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by vojtamolda** [comment]
Thanks, @samsonrosen ! 😊
