### ISSUE TITLE
Ranger/ Extender behaviour possible?

### ISSUE THREAD

**Issue by phenomeus** [vojtamolda/homebridge-bluetooth#28]
hi there, 

is your plugin able to act like an extender or ranger for BLE devices like "eve thermostat"? 

this plugin "https://github.com/grover/homebridge-ranger" does the trick but its not supported anymore and only hacked together… 

maybe you could have a look or two? ;) thanks in advance

**Comment by vojtamolda** [comment]
Hello @phenomeus,

I'm afraid I don't have the time to take a look at the moment. You'll probably have to "hack" it yourself 😉

Cheers,

  Vojta
