### ISSUE TITLE
Output signal strength (RSSI) for discovered devices

### ISSUE THREAD

**Issue by vojtamolda** [vojtamolda/homebridge-bluetooth#3]
Currently, the plugin only logs the name and address when a new BLE device is discovered. Per discussion in #2 it would be helpful to output the RSSI (signal strength in dB) as well.

![console](https://cloud.githubusercontent.com/assets/8467740/20715453/df4e4c6e-b614-11e6-9d4a-8671dd7487a6.png)

RSSI can be used to tell which peripheral device is closer to the central and also detect possible problems with a weak signal.

**Comment by vojtamolda** [comment]
Good to point to get started with this issue is around [line 94](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/source/platform.js#L94) in the `platform.js` file. I think that `nobleAccessory.advertisement` contains the RSSI value, but I'm not 100% sure. It may also be the `nobleAccessory` object itself.

Some of the [Noble examples](https://github.com/sandeepmistry/noble/blob/73a01ea52063cbaa5b2649250fae146be36588dc/examples/enter-exit.js) might come handy in figuring out these details.

**Comment by fYaH-r0ze** [comment]
Ok, I'll have a look at this one this week as well

**Comment by vojtamolda** [comment]
Perfect! Let me know if you get stuck somewhere.
