### ISSUE TITLE
Schlage bluetooth lock question

### ISSUE THREAD

**Issue by Vartkat** [vojtamolda/homebridge-bluetooth#35]
Hello,

I'm sure I'm missing something or this is not the right place to ask, nevertheless...

I Have a Raspberry Pi 4 running Home Assistant and a Schlage Sense lock (i.e. bluetooth).  
- The Lock is HomeKit compliant, 
- The Raspberry has bluetooth builtin... 
but
- Home Assistant doesn't know how to deal with a bluetooth lock 
- Home Assistant can deal with a Homekit lock, 

So you got my question : would your homebridge (I say _your_ because there was also a Homebridge addon for Home Assistant but I can't say if it has something to do with yours)... Would it be usefull to install your Homebridge on the Pi ? Would it make the Schlage lock visible as a HomeKit lock on the Wifi network ( which, I hope, would allow Home Assistant to see it)?

The Pi is running Ubuntu Server 20.04 and Home Assistant is running on Docker on the Ubuntu Server.

Thanks for your help

Regards

V.

**Comment by vojtamolda** [comment]
Hello @Vartkat,

Thanks for posting the question but this repository isn't what you're looking for. Honestly, I'm not sure where to point you. If the lock already works with HomeKit then this repository can't help you with anything.

The code here is meant as a tool for people who design their own electronic device. For example a DIY version of the Schlage lock. You can check out the examples there's also a thermometer or a lightbulb. Together with homebridge server you can make your own DIY devices controllable from your Apple devices.

Cheers and good luck with your project,

  Vojta

**Comment by Vartkat** [comment]
@vojtamolda . Thank you very much
