### ISSUE TITLE
Example for Open Sesame garage door opener

### ISSUE THREAD

**Issue by ddilbaz** [vojtamolda/homebridge-bluetooth#8]
Hi, could you give an example of a garage door with Bluetooth?

**Comment by vojtamolda** [comment]
Hello @ddilbaz, I'd love to include a garage door example, but I currently don't have a garage :smile:

Do you have a particular hardware you want to use in mind? Or do you mean just a general class of devices from [`HomeKitType.js`](https://github.com/KhaosT/HAP-NodeJS/blob/2ea9d761d9bd7593dd1949fec621ab085af5e567/lib/gen/HomeKitTypes.js#L2708)?

**Comment by ddilbaz** [comment]
Hi, Yes, I am using the "garage door-Open Sesame" product in the garage door. I use the product with the Applestore application. But it is not used with Siri. Homebridge- I've been working with your Bluetooth app, but I have not been successful. I need help especially in matters such as service, name. I tested the Bluetooth application with the Noble application. But I could not create Config.json file. I thank you in advance for your help.

iPad'imden gönderildi

**Comment by vojtamolda** [comment]
I'm afraid I won't be able to help very much here. Try talking to the "Open Sesame" people if they can provide you documentation about the _BLE_ service and characteristic UUIDs.

You can also try a general _BLE_ app like [LightBlue Explorer](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth-low-energy/id557428110?mt=8) that can read and write to any _BLE_ characteristic.

**Comment by ddilbaz** [comment]
Hello, I took the screenshot and I send it to you. Respects

![image](https://cloud.githubusercontent.com/assets/22238131/23589171/3056b288-01d1-11e7-98b9-34fc16d0a7a5.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589172/307afc6a-01d1-11e7-9a3a-b06b6da1e66b.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589173/30929b2c-01d1-11e7-8988-ac6eb80b7ac8.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589174/309633d6-01d1-11e7-8593-ae10eedee6ea.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589175/309bcab2-01d1-11e7-8bd6-f782cbfa927c.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589177/30a33dd8-01d1-11e7-82fc-d84c8d7d0713.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589178/30a5dc64-01d1-11e7-9b1d-608a861e1723.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589176/309eb42a-01d1-11e7-8b5f-24ffe2d7da8c.jpeg)
![image](https://cloud.githubusercontent.com/assets/22238131/23589180/30b8e7e6-01d1-11e7-9278-f56647bfe82a.jpeg)

iPad'

**Comment by vojtamolda** [comment]
Did you try playing around with different services and charactersitics? Were you able to send a command from the app to one of the characteristics, that would open and close the garage door? This would be the characteristic that you'd need to setup in `config.json` to make it work with _HomeKit_.
